"""add vote_count to character film starship

Revision ID: 9f97548ed59d
Revises: 32493b87f118
Create Date: 2026-07-22 14:58:47.024571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f97548ed59d'
down_revision: Union[str, Sequence[str], None] = '32493b87f118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    # ### end Alembic commands ###
