"""create initial tables

Revision ID: fb657f0513c3
Revises: 
Create Date: 2026-07-21 15:50:07.963652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb657f0513c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('mass', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('birth_year', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('homeworld', sa.String(), nullable=True),
    sa.Column('species', sa.JSON(), nullable=True),
    sa.Column('vehicles', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_birth_year'), ['birth_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_edited'), ['edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_eye_color'), ['eye_color'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_hair_color'), ['hair_color'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_height'), ['height'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_homeworld'), ['homeworld'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_mass'), ['mass'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_skin_color'), ['skin_color'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_swapi_id'), ['swapi_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_character_url'), ['url'], unique=False)

    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('opening_crawl', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('planets', sa.String(), nullable=True),
    sa.Column('vehicles', sa.JSON(), nullable=True),
    sa.Column('species', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_film_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_director'), ['director'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_edited'), ['edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_opening_crawl'), ['opening_crawl'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_planets'), ['planets'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_producer'), ['producer'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_swapi_id'), ['swapi_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_film_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_url'), ['url'], unique=False)

    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('passengers', sa.String(), nullable=True),
    sa.Column('cargo_capacity', sa.String(), nullable=True),
    sa.Column('consumables', sa.String(), nullable=True),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=True),
    sa.Column('mglt', sa.String(), nullable=True),
    sa.Column('starship_class', sa.String(), nullable=True),
    sa.Column('pilots', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_starship_cargo_capacity'), ['cargo_capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_consumables'), ['consumables'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_cost_in_credits'), ['cost_in_credits'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_crew'), ['crew'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_edited'), ['edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_hyperdrive_rating'), ['hyperdrive_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_length'), ['length'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_max_atmosphering_speed'), ['max_atmosphering_speed'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_mglt'), ['mglt'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_passengers'), ['passengers'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_starship_class'), ['starship_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_starship_swapi_id'), ['swapi_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_starship_url'), ['url'], unique=False)

    op.create_table('character_films',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'film_id')
    )
    op.create_table('character_starships',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'starship_id')
    )
    op.create_table('film_starships',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'starship_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_starships')
    op.drop_table('character_starships')
    op.drop_table('character_films')
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_starship_url'))
        batch_op.drop_index(batch_op.f('ix_starship_swapi_id'))
        batch_op.drop_index(batch_op.f('ix_starship_starship_class'))
        batch_op.drop_index(batch_op.f('ix_starship_passengers'))
        batch_op.drop_index(batch_op.f('ix_starship_name'))
        batch_op.drop_index(batch_op.f('ix_starship_model'))
        batch_op.drop_index(batch_op.f('ix_starship_mglt'))
        batch_op.drop_index(batch_op.f('ix_starship_max_atmosphering_speed'))
        batch_op.drop_index(batch_op.f('ix_starship_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_starship_length'))
        batch_op.drop_index(batch_op.f('ix_starship_id'))
        batch_op.drop_index(batch_op.f('ix_starship_hyperdrive_rating'))
        batch_op.drop_index(batch_op.f('ix_starship_edited'))
        batch_op.drop_index(batch_op.f('ix_starship_crew'))
        batch_op.drop_index(batch_op.f('ix_starship_created'))
        batch_op.drop_index(batch_op.f('ix_starship_cost_in_credits'))
        batch_op.drop_index(batch_op.f('ix_starship_consumables'))
        batch_op.drop_index(batch_op.f('ix_starship_cargo_capacity'))

    op.drop_table('starship')
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_film_url'))
        batch_op.drop_index(batch_op.f('ix_film_title'))
        batch_op.drop_index(batch_op.f('ix_film_swapi_id'))
        batch_op.drop_index(batch_op.f('ix_film_release_date'))
        batch_op.drop_index(batch_op.f('ix_film_producer'))
        batch_op.drop_index(batch_op.f('ix_film_planets'))
        batch_op.drop_index(batch_op.f('ix_film_opening_crawl'))
        batch_op.drop_index(batch_op.f('ix_film_id'))
        batch_op.drop_index(batch_op.f('ix_film_episode_id'))
        batch_op.drop_index(batch_op.f('ix_film_edited'))
        batch_op.drop_index(batch_op.f('ix_film_director'))
        batch_op.drop_index(batch_op.f('ix_film_created'))

    op.drop_table('film')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_url'))
        batch_op.drop_index(batch_op.f('ix_character_swapi_id'))
        batch_op.drop_index(batch_op.f('ix_character_skin_color'))
        batch_op.drop_index(batch_op.f('ix_character_name'))
        batch_op.drop_index(batch_op.f('ix_character_mass'))
        batch_op.drop_index(batch_op.f('ix_character_id'))
        batch_op.drop_index(batch_op.f('ix_character_homeworld'))
        batch_op.drop_index(batch_op.f('ix_character_height'))
        batch_op.drop_index(batch_op.f('ix_character_hair_color'))
        batch_op.drop_index(batch_op.f('ix_character_gender'))
        batch_op.drop_index(batch_op.f('ix_character_eye_color'))
        batch_op.drop_index(batch_op.f('ix_character_edited'))
        batch_op.drop_index(batch_op.f('ix_character_created'))
        batch_op.drop_index(batch_op.f('ix_character_birth_year'))

    op.drop_table('character')
    # ### end Alembic commands ###
